version: '3.8'

services:
  app-app-backend:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network

  app-app-frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - app-app-backend
    networks:
      - app-network

  app-app-mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
